# Generated by Django 2.1.7 on 2019-04-20 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theteam', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='First',
            new_name='first',
        ),
    ]
