# Generated by Django 2.1.7 on 2019-04-20 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theteam', '0002_auto_20190420_1748'),
    ]

    operations = [
        migrations.DeleteModel(
            name='team',
        ),
    ]
