# Generated by Django 2.1.7 on 2019-04-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('theteam', '0003_delete_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=15, verbose_name='发起人')),
                ('telephone', models.IntegerField(max_length=15, verbose_name='联系方式')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='邮箱可选')),
                ('competition', models.CharField(max_length=20, verbose_name='比赛')),
                ('teamer', models.CharField(max_length=55, verbose_name='现有队员')),
                ('description', models.CharField(max_length=100, verbose_name='需要描述')),
            ],
        ),
    ]
