# Generated by Django 2.1.7 on 2019-04-20 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theteam', '0004_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': '组队', 'verbose_name_plural': '组队'},
        ),
        migrations.AlterModelTable(
            name='team',
            table='team',
        ),
    ]
