# Generated by Django 2.1.7 on 2019-04-01 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginupin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='users',
        ),
    ]
