# Generated by Django 2.1.7 on 2019-04-02 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginupin', '0004_auto_20190402_2015'),
    ]

    operations = [
        migrations.DeleteModel(
            name='users',
        ),
    ]
