# Generated by Django 2.1.7 on 2019-04-02 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginupin', '0006_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='users',
        ),
    ]
