# Generated by Django 2.1.7 on 2019-04-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loginupin', '0007_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('user_phone', models.CharField(max_length=50)),
                ('user_password', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
