# Generated by Django 2.1.7 on 2019-04-25 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginupin', '0011_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IMG',
        ),
    ]
